# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 759f2feed4c3935f855519d3ef1547bd68c81f11eae8edc8e231744584f564a4f7241a9b0b9cff04eda33b2b1922862f0ff483581da51b0b005b226a7c19debd

test:
  secret_key_base: 416262755a07a84012fd74484a6a92df42542a77bcca8070165fb51cefa337e51b713c87a5260c1d38fbed9da7a4ff368a8cee27a6e47fdedad1a2bc90097cdd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
